version: "3"

services:

  demo.koala-lms.org:
    image: registry.gitlab.com/koala-lms/lms/demo:latest
    container_name: demo.koala-lms.org
    hostname: demo.koala-lms.org
    environment:
      LANGUAGE_CODE: 'fr-FR'
      TIME_ZONE: 'Europe/Paris'
      FIXTURE: "./fixtures/sample-fr.json"
      DEMO: 1
    ports:
      - 8080:8080
